# Generated by Django 5.2.17 on 2026-08-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stock_movement_number_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Customer and Supplier'), ('employee', 'Employee')], max_length=10),
        ),
    ]
