# Generated by Django 5.2.17 on 2026-08-26 04:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_journalentry_unique_business_journal_reference_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], max_length=10)),
                ('number', models.CharField(max_length=40)),
                ('document_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_documents', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_trade_documents', to='accounting.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_trade_documents', to='accounting.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_document', to='accounting.journalentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_documents', to='core.party')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_documents', to='accounting.fiscalperiod')),
            ],
            options={
                'ordering': ['-document_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.tradedocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_lines', to='core.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tradedocument',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='unique_business_trade_number'),
        ),
        migrations.AddConstraint(
            model_name='tradedocument',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='trade_document_nonnegative_total'),
        ),
        migrations.AddConstraint(
            model_name='tradeline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='trade_line_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='tradeline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='trade_line_nonnegative_price'),
        ),
    ]
