# Generated by Django 5.2.17 on 2026-08-28 14:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_money_receipts'),
        ('core', '0004_stock_movement_number_constraints'),
        ('operations', '0004_sale_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='core.business')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payment', to='accounting.journalentry')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_made', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments', to='accounting.account')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='operations.tradedocument')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payment', to='accounting.voucher')),
            ],
            options={
                'ordering': ['payment_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('business', 'number'), name='unique_business_purchase_payment_number'), models.UniqueConstraint(fields=('business', 'idempotency_key'), name='unique_business_purchase_payment_idempotency'), models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9]{8}$')), name='purchase_payment_number_format'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchase_payment_positive_amount')],
            },
        ),
    ]
