# Generated by Django 5.2.17 on 2026-08-28 19:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_voucher_voucher_type'),
        ('core', '0004_stock_movement_number_constraints'),
        ('operations', '0005_purchasepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSetoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('setoff_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_setoffs', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_setoffs_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_setoff', to='accounting.journalentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_setoffs', to='core.party')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_setoff', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-setoff_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseSetoffAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_setoff_allocations', to='operations.tradedocument')),
                ('setoff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_allocations', to='operations.balancesetoff')),
            ],
        ),
        migrations.CreateModel(
            name='SaleSetoffAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_setoff_allocations', to='operations.tradedocument')),
                ('setoff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='operations.balancesetoff')),
            ],
        ),
        migrations.AddConstraint(
            model_name='balancesetoff',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='unique_business_balance_setoff_number'),
        ),
        migrations.AddConstraint(
            model_name='balancesetoff',
            constraint=models.UniqueConstraint(fields=('business', 'idempotency_key'), name='unique_business_balance_setoff_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='balancesetoff',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9]{8}$')), name='balance_setoff_number_format'),
        ),
        migrations.AddConstraint(
            model_name='balancesetoff',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='balance_setoff_positive_total'),
        ),
        migrations.AddConstraint(
            model_name='purchasesetoffallocation',
            constraint=models.UniqueConstraint(fields=('setoff', 'purchase'), name='unique_setoff_purchase_allocation'),
        ),
        migrations.AddConstraint(
            model_name='purchasesetoffallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchase_setoff_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesetoffallocation',
            constraint=models.UniqueConstraint(fields=('setoff', 'sale'), name='unique_setoff_sale_allocation'),
        ),
        migrations.AddConstraint(
            model_name='salesetoffallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sale_setoff_allocation_positive'),
        ),
    ]
