# Generated by Django 5.2.17 on 2026-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_money_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('expense', 'Expense'), ('return', 'Return')], max_length=10),
        ),
    ]
