# Generated by Django 5.2.17 on 2026-08-28 20:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_voucher_voucher_type'),
        ('core', '0004_stock_movement_number_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('expense_date', models.DateField()),
                ('settlement', models.CharField(choices=[('paid', 'Paid now'), ('payable', 'Pay later')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records_created', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_records', to='accounting.account')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expense_record', to='accounting.journalentry')),
                ('payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrued_expense_records', to='accounting.account')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_records', to='core.party')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_expense_records', to='accounting.account')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expense_record', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='core.business')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payment', to='accounting.journalentry')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_payments_created', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payments', to='accounting.account')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payment', to='accounting.voucher')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.expenserecord')),
            ],
            options={
                'ordering': ['payment_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='expenserecord',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='unique_business_expense_number'),
        ),
        migrations.AddConstraint(
            model_name='expenserecord',
            constraint=models.UniqueConstraint(fields=('business', 'idempotency_key'), name='unique_business_expense_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='expenserecord',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9]{8}$')), name='expense_number_format'),
        ),
        migrations.AddConstraint(
            model_name='expenserecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='unique_business_expense_payment_number'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.UniqueConstraint(fields=('business', 'idempotency_key'), name='unique_business_expense_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9]{8}$')), name='expense_payment_number_format'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_payment_positive_amount'),
        ),
    ]
